### PR TITLE
add logo to readme fixes #37

### LINKED ISSUE #37: Use Tram-One Logo in Readme
## Summary
We should put the logo in the README. Other projects do it, and our logo is super-awesome!

## Other projects
- https://github.com/sindresorhus/eslint-plugin-unicorn
- https://github.com/sindresorhus/xo
- https://github.com/vuejs/vue

### PR DESCRIPTION
**Pull request by DanudeSandstorm**
Resolves #37 
~Needs this to be resolved first: Tram-One/tram-logo#2~

### CODE REVIEW

**Comment by JRJurman** [comment]
Oh no
image

**Comment by DanudeSandstorm** [comment]
Try this commit. Its hard to test this. Github keeps trying to cache it through camo or something. I'm not sure how to preserve the unicode, so I used rendered html from github.

**Comment by JRJurman** [comment]
Hmm... that's odd, I didn't realize it was the emoji, you can kill the emoji since we have the Logo now.

**Comment by JRJurman** [comment]
I'm not sure I'm a huge fan of the spacing here... (Sorry to be nit-picky)
@ethanjurman @chtinahow what do you guys think?

**Comment by JRJurman** [comment]
To clarify, to preview it, you can click "View" under the Files Changed tab
image

**Comment by DanudeSandstorm** [comment]
The problem is the preview doesn't always render because of some strangeness with github's caching using a "camo" cdn

There should have been a couple of line breaks in that hmm. (When I had it rendered correctly, it was like https://github.com/sindresorhus/eslint-plugin-unicorn )

**Comment by DanudeSandstorm** [comment]
This commit 60a5b77 may be what you're looking for

**Comment by ethanjurman** [comment]
Looks good but does that image have a white background on it? (Viewed it on mobile and it was noticeable)
image
Might be something that can't be fixed... but seems strange.

**Comment by JRJurman** [comment]
The white background might be because we are using an image tag... I wonder if using the svg tag would fix that.... Either way, I'm calling this good... any more and this ticket is going to labeled difficult :P 

Thanks for the work @DanudeSandstorm 👍

**Pull request merged**
